//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int Id { get; set; }
        public int CustomerTypeId { get; set; }
        public string Name { get; set; }
        public string CardId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
