//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int Id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
